services:
  db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_DB: billinho_db
      POSTGRES_USER: beatriz
      POSTGRES_PASSWORD: dev123
    ports:
      - '5432:5432'
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    networks:
      - compose-network

  rails:
    build: .
    container_name: 'rails-container'
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/application
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - compose-network
networks:
  compose-network:
    driver: bridge
