source 'https://rubygems.org'

ruby '3.0.2'

gem 'rails', '~> 7.1.2'

gem 'aasm', '~> 5.1', '>= 5.1.1'
gem 'bootsnap', require: false
gem 'cpf_faker'
gem 'faker'
gem 'pg', '~> 1.2'
gem 'puma', '>= 5.0'
gem 'viacep'

group :development, :test do
  gem 'rspec-rails', '> 6.1.0'
  gem 'shoulda-matchers'
  gem 'factory_bot_rails'
  gem 'dotenv-rails'
end

group :development do
  gem 'rubocop', require: false
end
