default: &default
  host: db
  adapter: postgresql
  encoding: unicode
  username: beatriz
  password: dev123

development:
  <<: *default
  database: billinho_db_development
test:
  <<: *default
  database: billinho_db_test
production:
  <<: *default
  database: billinho_db_production
