default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: beatriz
  password: dev123
  port: 5432

development:
  <<: *default
  database: billinho_db_development

test:
  <<: *default
  database: billinho_db_test

production:
  <<: *default
  database: billinho_db_production
